'use client';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { BookOpen, LayoutDashboard, NotebookPen, Layers3, PlaySquare, Users, Languages, Settings2, ArrowUpRight, Compass, ChevronRight, LogOut } from 'lucide-react';
import { SidebarProvider, Sidebar, SidebarHeader, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupLabel, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger, useSidebar } from '@/components/ui/sidebar';
import { useElevation } from './provider';
import { Logo, LanguagePicker, ProfileAvatar } from './shared';
function ShellInner({children,admin}:{children:React.ReactNode;admin:boolean}){const {tr,courses,user,role,signOut}=useElevation();const router=useRouter();const path=usePathname();const {setOpenMobile}=useSidebar();const links=admin?[
 ['/admin',tr('Overview','Resumen','Übersicht'),LayoutDashboard],['/admin/studies',tr('Study library','Biblioteca','Studienbibliothek'),BookOpen],['/admin/sessions',tr('Sessions & media','Sesiones y medios','Einheiten und Medien'),PlaySquare],['/admin/members',tr('Members','Miembros','Mitglieder'),Users],['/admin/languages',tr('Translations','Traducciones','Übersetzungen'),Languages],['/admin/settings',tr('Settings','Configuración','Einstellungen'),Settings2]
 ]:[['/member',tr('My overview','Mi resumen','Meine Übersicht'),LayoutDashboard],['/member/studies',tr('All studies','Todos los estudios','Alle Studien'),BookOpen],['/member/notes',tr('My notes','Mis notas','Meine Notizen'),NotebookPen]];
 const current=links.find(([href])=>href===path);return <><Sidebar className="elevation-sidebar"><SidebarHeader className="side-brand"><Logo light/><span className="workspace-label">{admin?tr('ADMIN STUDIO','ADMINISTRACIÓN','VERWALTUNG'):tr('THE LEARNING ROOM','EL AULA DE ESTUDIO','DER LERNRAUM')}</span></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel className="side-group-label">{admin?tr('WORKSPACE','ESPACIO DE TRABAJO','ARBEITSBEREICH'):tr('YOUR JOURNEY','TU RECORRIDO','DEIN LERNWEG')}</SidebarGroupLabel><SidebarMenu>{links.map(([href,label,Icon])=><SidebarMenuItem key={href as string}><SidebarMenuButton asChild isActive={path===href || href==='/member/studies'&&path.includes('/lesson/')} className="side-link"><Link href={href as string} onClick={()=>setOpenMobile(false)}>{typeof Icon!=='string'&&<Icon/>}<span>{label as string}</span>{href==='/admin/studies'&&<small>{courses.length}</small>}</Link></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup>{!admin&&<div className="side-journey"><Compass/><h3>{tr('One step at a time.','Un paso a la vez.','Ein Schritt nach dem anderen.')}</h3><p>{tr('Small moments in the Word. A life with deeper roots.','Momentos en la Palabra. Una vida con raíces más profundas.','Kleine Momente im Wort. Ein Leben mit tieferen Wurzeln.')}</p></div>}</SidebarContent><SidebarFooter className="side-footer">{!admin&&role==='admin'?<Link href="/admin" className="side-return">{tr('Back to admin studio','Volver a administración','Zurück zur Verwaltung')}<ArrowUpRight/></Link>:!admin?<Link href="/" className="side-return">{tr('Back to Elevation','Volver a Elevation','Zurück zu Elevation')}<ArrowUpRight/></Link>:null}<div className="side-profile"><ProfileAvatar/><div><strong>{user?.email||''}</strong><small>{role==='admin'?tr('Administrator','Administrador','Administrator'):tr('Member','Miembro','Mitglied')}</small></div><button type="button" className="side-signout" aria-label={tr('Sign out','Cerrar sesión','Abmelden')} onClick={async()=>{await signOut();router.push('/login');router.refresh()}}><LogOut/></button></div></SidebarFooter></Sidebar><div className="app-main"><header className="app-topbar"><div className="breadcrumb"><SidebarTrigger className="sidebar-toggle"/><span>Elevation</span><ChevronRight/><strong>{current?.[1] as string || tr('Study session','Sesión de estudio','Studieneinheit')}</strong></div><div className="app-top-right"><LanguagePicker/><span className="topbar-divider"/><ProfileAvatar className="small-avatar"/></div></header><main className="workspace-content">{children}</main><div className="workspace-footer">Elevation Bible Study <span>{tr('A higher perspective. A deeper understanding.','Una perspectiva más alta. Una comprensión más profunda.','Eine höhere Perspektive. Ein tieferes Verständnis.')}</span></div></div></>}
export function AppShell({children,admin=false}:{children:React.ReactNode;admin?:boolean}){return <SidebarProvider className="elevation-app" style={{'--sidebar-width':'250px'} as React.CSSProperties}><ShellInner admin={admin}>{children}</ShellInner></SidebarProvider>}
