export type Language = 'en' | 'es' | 'de';
export type Localized = [string, string, string];
export const pick = (text: Localized, lang: Language) => text[lang === 'en' ? 0 : lang === 'es' ? 1 : 2];
export type Course = { id: string; title: Localized; subtitle: Localized; description: Localized; count: number; theme: string; category: 'foundations' | 'new-testament' | 'prophecy'; status: 'preview' | 'draft'; lessons: Localized[] };
export const initialCourses: Course[] = [
 {id:'interpretation',title:['Bible Interpretation 101','Interpretación bíblica 101','Bibelauslegung 101'],subtitle:['The foundation for everything.','El fundamento de todo.','Das Fundament für alles.'],description:['The simple rules behind every study. Learn to read in context, follow the argument, and check the work for yourself.','Las reglas sencillas detrás de cada estudio. Aprende a leer en contexto, seguir el argumento y comprobarlo por ti mismo.','Die einfachen Regeln hinter jedem Studium. Lerne, im Kontext zu lesen, dem Gedankengang zu folgen und selbst zu prüfen.'],count:1,theme:'foundation',category:'foundations',status:'preview',lessons:[['The thousand-foot view','La perspectiva desde lo alto','Der Blick aus der Höhe']]},
 {id:'romans',title:['Romans','Romanos','Römer'],subtitle:['The gospel. One complete picture.','El evangelio. Un panorama completo.','Das Evangelium. Ein ganzes Bild.'],description:['From the first verse to the last, read Romans as one continuous argument about the gospel.','Desde el primer versículo hasta el último, lee Romanos como un argumento continuo acerca del evangelio.','Lies den Römerbrief vom ersten bis zum letzten Vers als einen zusammenhängenden Gedankengang über das Evangelium.'],count:12,theme:'romans',category:'new-testament',status:'preview',lessons:[['The gospel in context','El evangelio en contexto','Das Evangelium im Kontext'],['Our need for righteousness','Nuestra necesidad de justicia','Unser Bedürfnis nach Gerechtigkeit'],['The faith of Abraham','La fe de Abraham','Der Glaube Abrahams'],['Peace with God','Paz con Dios','Frieden mit Gott'],['A new way to live','Una nueva forma de vivir','Ein neuer Weg zu leben'],['Life in the Spirit','La vida en el Espíritu','Leben im Geist'],['The promise of God','La promesa de Dios','Die Verheißung Gottes'],['Grace and Israel','La gracia e Israel','Gnade und Israel'],['The mercy of God','La misericordia de Dios','Gottes Barmherzigkeit'],['A living sacrifice','Un sacrificio vivo','Ein lebendiges Opfer'],['Love in practice','El amor en la práctica','Liebe in der Praxis'],['One gospel, one people','Un evangelio, un pueblo','Ein Evangelium, ein Volk']]},
 {id:'galatians',title:['Galatians','Gálatas','Galater'],subtitle:['From rules to a life of faith.','De las reglas a una vida de fe.','Von Regeln zu einem Leben im Glauben.'],description:['A practical look at the law, grace, and what it means to live by the law of Christ.','Una mirada práctica a la ley, la gracia y lo que significa vivir bajo la ley de Cristo.','Ein praktischer Blick auf Gesetz, Gnade und ein Leben nach dem Gesetz Christi.'],count:8,theme:'galatians',category:'new-testament',status:'preview',lessons:[['One gospel','Un solo evangelio','Ein Evangelium'],['Called by grace','Llamados por gracia','Durch Gnade berufen'],['Justified by faith','Justificados por la fe','Gerecht durch Glauben'],['The purpose of the law','El propósito de la ley','Der Zweck des Gesetzes'],['Children of promise','Hijos de la promesa','Kinder der Verheißung'],['Freedom in Christ','Libertad en Cristo','Freiheit in Christus'],['Walking in the Spirit','Andar en el Espíritu','Im Geist wandeln'],['The law of Christ','La ley de Cristo','Das Gesetz Christi']]},
 {id:'colossians',title:['Colossians','Colosenses','Kolosser'],subtitle:['A clearer view of who Jesus is.','Una visión más clara de Jesús.','Ein klarerer Blick auf Jesus.'],description:['See the fullness of Christ, including a focused study on the oneness of God.','Descubre la plenitud de Cristo, con un estudio enfocado en la unicidad de Dios.','Entdecke die Fülle Christi, mit einem Schwerpunkt auf der Einheit Gottes.'],count:9,theme:'colossians',category:'new-testament',status:'preview',lessons:[['Christ at the center','Cristo en el centro','Christus im Mittelpunkt'],['The image of the invisible God','La imagen del Dios invisible','Das Bild des unsichtbaren Gottes'],['Reconciled through Christ','Reconciliados por Cristo','Versöhnt durch Christus'],['Rooted and built up','Arraigados y edificados','Verwurzelt und aufgebaut'],['The fullness of God','La plenitud de Dios','Die Fülle Gottes'],['Complete in Him','Completos en Él','Vollständig in ihm'],['Set your mind above','Poned la mira arriba','Richtet euren Sinn nach oben'],['Putting on the new life','Vestidos de la nueva vida','Das neue Leben anziehen'],['Living the message','Vivir el mensaje','Die Botschaft leben']]},
 {id:'revelation',title:['Revelation & the End Times','Apocalipsis y el fin de los tiempos','Offenbarung und die Endzeit'],subtitle:['The whole picture. Finally in focus.','Todo el panorama. Por fin claro.','Das ganze Bild. Endlich klar.'],description:['Put the prophets, the words of Jesus, and Revelation in their proper order. Follow the text and see how the story connects.','Ordena los profetas, las palabras de Jesús y Apocalipsis. Sigue el texto y descubre cómo se conecta la historia.','Ordne die Propheten, die Worte Jesu und die Offenbarung ein. Folge dem Text und erkenne die Zusammenhänge.'],count:33,theme:'revelation',category:'prophecy',status:'preview',lessons:[['A revelation of Jesus Christ','Una revelación de Jesucristo','Eine Offenbarung Jesu Christi'],['Reading prophecy in context','Leer la profecía en contexto','Prophetie im Kontext lesen'],['The letters to the churches','Las cartas a las iglesias','Die Briefe an die Gemeinden'],['The throne and the Lamb','El trono y el Cordero','Der Thron und das Lamm'],['Seeing the sequence','Entender la secuencia','Die Reihenfolge erkennen'],['The words of Jesus','Las palabras de Jesús','Die Worte Jesu']]},
 {id:'gospels-acts',title:['The Gospels & Acts','Los Evangelios y Hechos','Die Evangelien und Apostelgeschichte'],subtitle:['The next chapter is coming.','El próximo capítulo se acerca.','Das nächste Kapitel kommt.'],description:['The next series in the wide-angle walk through the New Testament. Currently in production.','La próxima serie del recorrido panorámico por el Nuevo Testamento. Actualmente en producción.','Die nächste Reihe unserer Reise durch das Neue Testament. Derzeit in Vorbereitung.'],count:0,theme:'gospels',category:'new-testament',status:'draft',lessons:[]}
];
export const previewProfile = { name: 'Troy Johnson', firstName: 'Troy', initials: 'TJ', image: '/images/troy-johnson.jpg' };
export const sampleMembers = [
 {id:1,name:previewProfile.name,email:'troy@example.com',lang:'EN',plan:'Free',progress:35,active:true,initials:previewProfile.initials},
 {id:2,name:'Sofia Reyes',email:'sofia@example.com',lang:'ES',plan:'Supporter',progress:72,active:true,initials:'SR'},
 {id:3,name:'Daniel Weber',email:'daniel@example.com',lang:'DE',plan:'Free',progress:48,active:true,initials:'DW'},
 {id:4,name:'Grace Williams',email:'grace@example.com',lang:'EN',plan:'Supporter',progress:91,active:true,initials:'GW'},
 {id:5,name:'Mateo Garcia',email:'mateo@example.com',lang:'ES',plan:'Free',progress:12,active:false,initials:'MG'},
 {id:6,name:'Emma Fischer',email:'emma@example.com',lang:'DE',plan:'Free',progress:60,active:true,initials:'EF'}
];
