'use client';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { useState } from 'react';
import { ArrowRight, ArrowDown, Play, Check, BookOpen, LayoutDashboard, ShieldCheck, Search, Globe2 } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Input } from '@/components/ui/input';
import { useElevation } from './provider';
import { PublicHeader, PublicFooter, Eyebrow, CourseCard, VideoModal } from './shared';
import { supabaseBrowser } from '@/lib/supabase/client';
export function HomePage(){const {tr,lang,setLang,courses}=useElevation();const [video,setVideo]=useState(false);const principles=[
 [tr('Context first','El contexto primero','Kontext zuerst'),tr('Read each passage inside the argument it belongs to.','Lee cada pasaje dentro del argumento al que pertenece.','Lies jeden Abschnitt in seinem Zusammenhang.')],
 [tr('The proper order','El orden correcto','Die richtige Reihenfolge'),tr('Lay the events in sequence. Let the bigger picture emerge.','Ordena los acontecimientos y descubre el panorama completo.','Ordne die Ereignisse und erkenne das Gesamtbild.')],
 [tr('Scripture with Scripture','Escritura con Escritura','Schrift mit Schrift'),tr('Let the Bible interpret itself before reaching for outside theory.','Deja que la Biblia se interprete a sí misma antes de buscar teorías externas.','Lass die Bibel sich selbst auslegen, bevor du externe Theorien heranziehst.')],
 [tr('History & language','Historia e idioma','Geschichte und Sprache'),tr('Understand the audience, the culture, and the words that matter.','Comprende la audiencia, la cultura y las palabras que importan.','Verstehe die Adressaten, die Kultur und die entscheidenden Worte.')],
 [tr('Clarity over speculation','Claridad antes que especulación','Klarheit statt Spekulation'),tr('Where something is uncertain, we say so. Open your Bible. Check the work.','Si algo es incierto, lo decimos. Abre tu Biblia. Comprueba el estudio.','Wo etwas unsicher ist, sagen wir es. Öffne deine Bibel und prüfe selbst.')]
 ];return <><PublicHeader/><main><section className="hero"><img className="hero-image" src="/images/summit.webp" alt="A mountain summit rising above the clouds at dawn" fetchPriority="high"/><div className="site-container hero-body"><Eyebrow gold>{tr('The Thousand-Foot View','La perspectiva desde lo alto','Der Blick aus der Höhe')}</Eyebrow><h1>{tr('A higher perspective.','Una perspectiva más alta.','Eine höhere Perspektive.')}<em>{tr('A deeper understanding.','Una comprensión más profunda.','Ein tieferes Verständnis.')}</em></h1><p className="hero-description">{tr('Step back, and Scripture snaps into focus. Discover the Bible book by book, in order, in context — until the whole picture comes together.','Da un paso atrás y la Escritura cobra sentido. Descubre la Biblia libro por libro, en orden y en contexto, hasta ver el panorama completo.','Tritt einen Schritt zurück und die Schrift wird klar. Entdecke die Bibel Buch für Buch, in ihrer Reihenfolge und im Kontext — bis sich das ganze Bild erschließt.')}</p><div className="hero-actions"><Link className="button gold" href="/member/lesson/revelation">{tr('Begin your study','Comienza tu estudio','Beginne dein Studium')}<ArrowRight/></Link><button className="hero-watch" onClick={()=>setVideo(true)}><span className="play-ring"><Play/></span>{tr('Discover Elevation','Descubre Elevation','Elevation entdecken')}</button></div><div className="hero-caption" aria-hidden="true"><div>{tr('A new altitude','Una nueva altura','Eine neue Höhe')}<strong>{tr('The same truth.','La misma verdad.','Dieselbe Wahrheit.')}</strong></div></div><div className="hero-bottom"><p>{tr('One Word. A world of understanding.','Una Palabra. Un mundo de comprensión.','Ein Wort. Eine Welt des Verstehens.')}<span>EN / ES / DE</span></p><a href="#studies">{tr('Explore the studies','Explora los estudios','Studien entdecken')}<ArrowDown/></a></div></div></section>
<section className="section-space" id="studies"><div className="site-container"><div className="section-heading"><div><Eyebrow>{tr('Your journey starts here','Tu recorrido comienza aquí','Deine Reise beginnt hier')}</Eyebrow><h2>{tr('An open Bible. A clearer picture.','Una Biblia abierta. Una visión más clara.','Eine offene Bibel. Ein klareres Bild.')}</h2></div><Link className="text-link" href="/studies">{tr('Explore all studies','Explorar todos los estudios','Alle Studien entdecken')}<ArrowRight/></Link></div><div className="study-grid">{courses.slice(0,3).map((c,i)=><CourseCard key={c.id} course={c} index={i}/>)}</div><div className="feature-series"><img src="/images/scripture.webp" alt="An open Bible illuminated by a quiet shaft of sunlight" loading="lazy"/><div><Eyebrow gold>{tr('The flagship series · 33 sessions','La serie principal · 33 sesiones','Die Schwerpunktreihe · 33 Einheiten')}</Eyebrow><h2>{tr('Revelation. Without the speculation.','Apocalipsis. Sin especulación.','Offenbarung. Ohne Spekulation.')}</h2><p>{tr('The prophets. The words of Jesus. The book of Revelation. Placed in order, until the whole story becomes clear.','Los profetas. Las palabras de Jesús. El libro de Apocalipsis. En orden, hasta que toda la historia sea clara.','Die Propheten. Die Worte Jesu. Das Buch der Offenbarung. In ihrer Reihenfolge, bis die ganze Geschichte klar wird.')}</p><Link href="/member/lesson/revelation" className="button gold">{tr('Explore the series','Explorar la serie','Die Reihe entdecken')}<ArrowRight/></Link></div><span className="feature-symbol">01 — 33 / {tr('THE FULL PICTURE','EL PANORAMA COMPLETO','DAS GANZE BILD')}</span></div></div></section>
<section className="approach-section section-space" id="approach"><div className="site-container approach-grid"><div><Eyebrow>{tr('A different way to study','Una forma diferente de estudiar','Ein anderer Weg zu lernen')}</Eyebrow><h2>{tr('You don’t need a seminary degree. Just the right','No necesitas un título de seminario. Solo la','Du brauchst keinen theologischen Abschluss. Nur die richtige')} <em>{tr('altitude.','perspectiva.','Perspektive.')}</em></h2><p>{tr('Most teaching zooms into a single verse and loses the thread. We step back. Each book has an overarching theme. See it, and individual passages begin to make sense.','A menudo la enseñanza se enfoca en un versículo y pierde el hilo. Nosotros damos un paso atrás. Cada libro tiene un tema central. Al verlo, los pasajes empiezan a cobrar sentido.','Oft konzentriert sich die Lehre auf einen Vers und verliert den Zusammenhang. Wir treten zurück. Jedes Buch hat ein übergeordnetes Thema. Erkenne es, und einzelne Stellen ergeben Sinn.')}</p><p>{tr('A legally trained mind. An open Bible. Every conclusion grounded in the text, so you can see how it was reached.','Una mente formada en derecho. Una Biblia abierta. Cada conclusión basada en el texto, para que veas cómo se llegó a ella.','Juristisch geschultes Denken. Eine offene Bibel. Jede Schlussfolgerung im Text begründet, damit du sie nachvollziehen kannst.')}</p><Link href="/member/lesson/revelation" className="text-link">{tr('Start with Revelation & the End Times','Comienza con Apocalipsis y el fin de los tiempos','Beginne mit Offenbarung und der Endzeit')}<ArrowRight/></Link></div><div className="principles">{principles.map(([title,body],i)=><article className="principle" key={i}><span className="index">0{i+1}</span><div><h3>{title}</h3><p>{body}</p></div></article>)}</div></div></section>
<section id="membership" className="section-space"><div className="site-container membership-layout"><div className="membership-intro"><Eyebrow>{tr('A place for everyone','Un lugar para todos','Ein Platz für alle')}</Eyebrow><h2>{tr('The Word is for everyone. The door is open.','La Palabra es para todos. La puerta está abierta.','Das Wort ist für alle. Die Tür ist offen.')}</h2><p>{tr('No one should have to pay to learn. Study freely. And if the teaching feeds you, help make the next lesson possible.','Nadie debería pagar para aprender. Estudia libremente. Y si la enseñanza te nutre, ayuda a hacer posible la próxima lección.','Niemand sollte für das Lernen bezahlen müssen. Studiere kostenlos. Und wenn dir die Lehre hilft, ermögliche die nächste Lektion.')}</p></div><div><div className="plans"><article className="plan"><h3>{tr('The student','El estudiante','Lernende')}</h3><div className="price">$0<small> / {tr('always','siempre','immer')}</small></div><ul>{[tr('Full study library','Biblioteca completa','Vollständige Bibliothek'),tr('Video & audio lessons','Lecciones de video y audio','Video- und Audiolektionen'),tr('Your own learning journey','Tu propio recorrido','Dein persönlicher Lernweg'),tr('English, Spanish & German','Inglés, español y alemán','Englisch, Spanisch und Deutsch')].map(t=><li key={t}><Check/>{t}</li>)}</ul><Link href="/login" className="button dark">{tr('Begin for free','Empieza gratis','Kostenlos beginnen')}<ArrowRight/></Link></article><article className="plan supporter"><h3>{tr('The supporter','El colaborador','Unterstützende')}</h3><div className="price">$7<small> / {tr('month','mes','Monat')}</small></div><ul>{[tr('Everything in the free account','Todo lo de la cuenta gratuita','Alles aus dem kostenlosen Konto'),tr('Downloadable outlines','Guías descargables','Gliederungen zum Download'),tr('Early access to new lessons','Acceso anticipado','Früher Zugang zu Lektionen'),tr('Members-only deep dives','Estudios profundos exclusivos','Exklusive Vertiefungen')].map(t=><li key={t}><Check/>{t}</li>)}</ul><span className="coming-soon">{tr('Coming soon','Próximamente','Demnächst')}</span></article></div><p className="support-note">{tr('An independent teaching ministry. Supporter membership is not yet open. Contributions are not tax-deductible.','Un ministerio de enseñanza independiente. La membresía de apoyo aún no está abierta. Las contribuciones no son deducibles de impuestos.','Ein unabhängiger Lehrdienst. Die Fördermitgliedschaft ist noch nicht verfügbar. Beiträge sind nicht steuerlich absetzbar.')}</p></div></div></section>
<section className="language-band"><div className="site-container"><div><h2>{tr('One message. Beyond borders.','Un mensaje. Más allá de las fronteras.','Eine Botschaft. Über Grenzen hinweg.')}</h2><p>{tr('The same study, in the language that speaks to you.','El mismo estudio, en el idioma que habla a tu corazón.','Dasselbe Studium in der Sprache, die dich erreicht.')}</p></div><div><div className="language-choices">{([['en','English'],['es','Español'],['de','Deutsch']] as const).map(([code,label])=><button key={code} className={`language-choice ${lang===code?'active':''}`} onClick={()=>setLang(code)}><span>{code.toUpperCase()}</span>{label}</button>)}</div><p>{tr('Urdu & Pashto translations in progress','Traducciones al urdu y pastún en curso','Übersetzungen in Urdu und Paschtu in Arbeit')}</p></div></div></section>
<section id="about" className="section-space"><div className="site-container teacher-grid"><div className="teacher-signature"><img className="teacher-portrait" src="/images/william-fussell.jpg" alt="Rev. William Fussell, JD"/><h3>Rev. William Fussell, JD</h3><p>{tr('PASTOR · MISSIONARY · TEACHER','PASTOR · MISIONERO · MAESTRO','PASTOR · MISSIONAR · LEHRER')}</p></div><div className="teacher-body"><Eyebrow>{tr('Meet your teacher','Conoce a tu maestro','Lerne deinen Lehrer kennen')}</Eyebrow><h2>{tr('A lifetime of study. A heart for making it clear.','Una vida de estudio. Un corazón para enseñar con claridad.','Ein Leben lang studieren. Mit Herz für Klarheit.')}</h2><p>{tr('Rev. William Fussell has spent more than 30 years helping people open their Bible and understand it. From planting churches in Poland to teaching the New Testament in Chile, the calling has stayed the same: make the Word accessible.','El Rev. William Fussell ha dedicado más de 30 años a ayudar a las personas a abrir su Biblia y comprenderla. Desde fundar iglesias en Polonia hasta enseñar el Nuevo Testamento en Chile, el llamado sigue siendo el mismo: hacer accesible la Palabra.','Rev. William Fussell hilft seit über 30 Jahren Menschen, ihre Bibel zu öffnen und zu verstehen. Von Gemeindegründungen in Polen bis zum Unterricht über das Neue Testament in Chile bleibt seine Berufung dieselbe: das Wort zugänglich zu machen.')}</p><p>{tr('His Juris Doctor trained him to read carefully, weigh the evidence, and distinguish what is proven from what is speculation. That same care shapes every Elevation study.','Su doctorado en derecho lo formó para leer con cuidado, sopesar las pruebas y distinguir lo demostrado de la especulación. Ese mismo cuidado define cada estudio de Elevation.','Sein Jurastudium lehrte ihn, sorgfältig zu lesen, Belege abzuwägen und Gesichertes von Spekulation zu unterscheiden. Diese Sorgfalt prägt jedes Elevation-Studium.')}</p><div className="credentials"><span>Texas Bible College</span><span>JD · McGeorge School of Law</span><span>{tr('U.S. Army veteran','Veterano del Ejército de EE. UU.','Veteran der U.S. Army')}</span><span>EN · ES · DE</span></div></div></div></section></main><PublicFooter/><VideoModal open={video} setOpen={setVideo}/></>}
export function StudyCatalog({member=false}:{member?:boolean}){const {courses,tr,tx}=useElevation();const [category,setCategory]=useState('all');const [search,setSearch]=useState('');const filtered=courses.filter(c=>(category==='all'||c.category===category)&&`${tx(c.title)} ${tx(c.description)}`.toLowerCase().includes(search.toLowerCase()));return <><div className="catalog-tools"><Tabs className="filter-tabs" value={category} onValueChange={setCategory}><TabsList aria-label={tr('Study category','Categoría del estudio','Studienkategorie')}>{[['all',tr('All studies','Todos','Alle Studien')],['foundations',tr('Foundations','Fundamentos','Grundlagen')],['new-testament',tr('New Testament','Nuevo Testamento','Neues Testament')],['prophecy',tr('Prophecy','Profecía','Prophetie')]].map(([id,label])=><TabsTrigger key={id} value={id}>{label}</TabsTrigger>)}</TabsList></Tabs><label className="search-box"><Search/><input placeholder={tr('Find a study…','Busca un estudio…','Studie suchen…')} aria-label={tr('Search studies','Buscar estudios','Studien suchen')} value={search} onChange={e=>setSearch(e.target.value)}/></label></div>{filtered.length?<div className="study-grid catalog-grid">{filtered.map((c,i)=><CourseCard course={c} key={c.id} index={courses.indexOf(c)} member={member}/>)}</div>:<div className="empty-state"><Search/><h3>{tr('No studies found','No se encontraron estudios','Keine Studien gefunden')}</h3><p>{tr('Try another title or choose a different category.','Prueba otro título o elige otra categoría.','Versuche einen anderen Titel oder eine andere Kategorie.')}</p><button className="button outline" onClick={()=>{setSearch('');setCategory('all')}}>{tr('Clear filters','Borrar filtros','Filter zurücksetzen')}</button></div>}<p className="catalog-note">{tr('Explore the curriculum preview. Video and audio lessons will be added as the platform launches.','Explora la vista previa del programa. Las lecciones en video y audio se añadirán al lanzar la plataforma.','Erkunde die Programmvorschau. Video- und Audiolektionen werden zum Start der Plattform ergänzt.')}</p></>}
export function StudiesPage(){const {tr}=useElevation();return <><PublicHeader/><main><div className="catalog-hero"><div className="site-container"><Eyebrow>{tr('The study library','La biblioteca de estudios','Die Studienbibliothek')}</Eyebrow><h1>{tr('Find your next perspective.','Encuentra tu próxima perspectiva.','Entdecke deine nächste Perspektive.')}</h1><p>{tr('Pick a book. Follow the story. Each session brings you one step closer to seeing the whole picture.','Elige un libro. Sigue la historia. Cada sesión te acerca un paso más al panorama completo.','Wähle ein Buch. Folge der Geschichte. Jede Einheit bringt dich dem Gesamtbild einen Schritt näher.')}</p></div></div><section className="site-container section-space"><StudyCatalog/></section></main><PublicFooter/></>}
export function LoginPage(){
 const {tr}=useElevation();
 const router=useRouter();
 const params=useSearchParams();
 const [email,setEmail]=useState('');
 const [password,setPassword]=useState('');
 const [error,setError]=useState('');
 const [submitting,setSubmitting]=useState(false);
 const submit=async(e:React.FormEvent)=>{
  e.preventDefault();setSubmitting(true);setError('');
  const supabase=supabaseBrowser();
  const {data,error:signInError}=await supabase.auth.signInWithPassword({email,password});
  if(signInError){setSubmitting(false);setError(tr('Incorrect email or password.','Correo o contraseña incorrectos.','Falsche E-Mail oder falsches Passwort.'));return}
  const {data:profile}=await supabase.from('profiles').select('role').eq('id',data.user.id).single();
  const from=params.get('from');
  router.push(from||(profile?.role==='admin'?'/admin':'/member'));
  router.refresh();
 };
 return <><PublicHeader/><main className="login-page"><div className="login-art"><Eyebrow gold>Elevation Bible Study</Eyebrow><div><h2>{tr('The next chapter','El próximo capítulo','Das nächste Kapitel')}<br/><em>{tr('starts with you.','comienza contigo.','beginnt mit dir.')}</em></h2><p>{tr('A place to slow down, open the Word, and see with a little more clarity.','Un lugar para hacer una pausa, abrir la Palabra y ver con más claridad.','Ein Ort, um innezuhalten, das Wort zu öffnen und klarer zu sehen.')}</p></div><p>“Rightly dividing the word of truth.”<br/>2 Timothy 2:15 · KJV</p></div><form className="login-form" onSubmit={submit}><Eyebrow>{tr('Welcome back','Bienvenido de nuevo','Willkommen zurück')}</Eyebrow><h1>{tr('Sign in to Elevation.','Inicia sesión en Elevation.','Bei Elevation anmelden.')}</h1><p>{tr('Enter your email and password to continue.','Ingresa tu correo y contraseña para continuar.','Gib deine E-Mail und dein Passwort ein, um fortzufahren.')}</p><label className="auth-field">{tr('Email','Correo','E-Mail')}<Input type="email" required value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label className="auth-field">{tr('Password','Contraseña','Passwort')}<Input type="password" required value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label>{error&&<p className="auth-error">{error}</p>}<button className="button dark" type="submit" disabled={submitting}>{submitting?tr('Signing in…','Iniciando sesión…','Anmeldung…'):tr('Sign in','Iniciar sesión','Anmelden')}<ArrowRight/></button><p className="small-note"><ShieldCheck/>{tr('New here?','¿Nuevo aquí?','Neu hier?')} <Link href="/signup">{tr('Create a member account','Crear una cuenta de miembro','Mitgliedskonto erstellen')}</Link></p></form></main></>}

export function SignupPage(){
 const {tr}=useElevation();
 const router=useRouter();
 const [name,setName]=useState('');
 const [email,setEmail]=useState('');
 const [password,setPassword]=useState('');
 const [error,setError]=useState('');
 const [submitting,setSubmitting]=useState(false);
 const [sent,setSent]=useState(false);
 const submit=async(e:React.FormEvent)=>{
  e.preventDefault();setSubmitting(true);setError('');
  const supabase=supabaseBrowser();
  const {data,error:signUpError}=await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});
  setSubmitting(false);
  if(signUpError){setError(signUpError.message);return}
  if(data.session){router.push('/member');router.refresh();return}
  setSent(true);
 };
 if(sent)return <><PublicHeader/><main className="login-page"><div className="login-art"><Eyebrow gold>Elevation Bible Study</Eyebrow><div><h2>{tr('Almost there.','Casi listo.','Fast geschafft.')}</h2><p>{tr('Check your email to confirm your account, then sign in.','Revisa tu correo para confirmar tu cuenta y luego inicia sesión.','Bestätige dein Konto per E-Mail und melde dich dann an.')}</p></div></div><div className="login-form"><Eyebrow>{tr('Confirm your email','Confirma tu correo','Bestätige deine E-Mail')}</Eyebrow><h1>{tr('We sent you a link.','Te enviamos un enlace.','Wir haben dir einen Link gesendet.')}</h1><p>{email}</p><Link className="button dark" href="/login">{tr('Back to sign in','Volver a iniciar sesión','Zurück zur Anmeldung')}</Link></div></main></>
 return <><PublicHeader/><main className="login-page"><div className="login-art"><Eyebrow gold>Elevation Bible Study</Eyebrow><div><h2>{tr('The next chapter','El próximo capítulo','Das nächste Kapitel')}<br/><em>{tr('starts with you.','comienza contigo.','beginnt mit dir.')}</em></h2><p>{tr('A place to slow down, open the Word, and see with a little more clarity.','Un lugar para hacer una pausa, abrir la Palabra y ver con más claridad.','Ein Ort, um innezuhalten, das Wort zu öffnen und klarer zu sehen.')}</p></div><p>“Rightly dividing the word of truth.”<br/>2 Timothy 2:15 · KJV</p></div><form className="login-form" onSubmit={submit}><Eyebrow>{tr('Join Elevation','Únete a Elevation','Werde Teil von Elevation')}</Eyebrow><h1>{tr('Create your account.','Crea tu cuenta.','Erstelle dein Konto.')}</h1><p>{tr('Get your own member dashboard to track studies and notes.','Obtén tu propio panel de miembro para tus estudios y notas.','Erhalte dein eigenes Mitgliederdashboard für Studien und Notizen.')}</p><label className="auth-field">{tr('Name','Nombre','Name')}<Input required value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></label><label className="auth-field">{tr('Email','Correo','E-Mail')}<Input type="email" required value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label className="auth-field">{tr('Password','Contraseña','Passwort')}<Input type="password" required minLength={6} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/></label>{error&&<p className="auth-error">{error}</p>}<button className="button dark" type="submit" disabled={submitting}>{submitting?tr('Creating account…','Creando cuenta…','Konto wird erstellt…'):tr('Create account','Crear cuenta','Konto erstellen')}<ArrowRight/></button><p className="small-note"><ShieldCheck/>{tr('Already have an account?','¿Ya tienes una cuenta?','Bereits ein Konto?')} <Link href="/login">{tr('Sign in','Iniciar sesión','Anmelden')}</Link></p></form></main></>}
