'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { ArrowRight, ArrowUpRight, BookOpen, Globe2, LayoutDashboard, Menu, Play, X, Mountain } from 'lucide-react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Sheet, SheetClose, SheetContent, SheetTitle, SheetTrigger } from '@/components/ui/sheet';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Progress } from '@/components/ui/progress';
import { useElevation } from './provider';
import { previewProfile, type Course, type Language } from './data';
import { Avatar, AvatarFallback } from '@/components/ui/avatar';
export function Logo({light=false}:{light?:boolean}){return <Link className={`logo ${light?'light':''}`} href="/" aria-label="Elevation Bible Study home"><img src="/images/elevation-logo.png" width="1584" height="396" alt="Elevation Bible Study"/></Link>}
export function ProfileAvatar({className=''}:{className?:string}){const {user}=useElevation();const initials=(user?.email||'').slice(0,2).toUpperCase()||previewProfile.initials;return <Avatar className={`avatar profile-avatar ${className}`}><AvatarFallback>{initials}</AvatarFallback></Avatar>}
export function LanguagePicker(){const {lang,setLang,tr}=useElevation();return <Select value={lang} onValueChange={v=>setLang(v as Language)}><SelectTrigger className="language-trigger" aria-label={tr('Language','Idioma','Sprache')}><Globe2/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="en">EN</SelectItem><SelectItem value="es">ES</SelectItem><SelectItem value="de">DE</SelectItem></SelectContent></Select>}
export function Eyebrow({children,gold=false}:{children:React.ReactNode;gold?:boolean}){return <div className={`eyebrow ${gold?'gold-text':''}`}><span className="rule"/>{children}</div>}
export function PublicHeader(){const {tr}=useElevation();const path=usePathname();const links=[['/',tr('Home','Inicio','Startseite')],['/studies',tr('The studies','Los estudios','Die Studien')],['/#approach',tr('Our approach','Nuestro enfoque','Unser Ansatz')],['/#about',tr('The teacher','El maestro','Der Lehrer')],['/#membership',tr('Membership','Membresía','Mitgliedschaft')],['/contact',tr('Contact','Contacto','Kontakt')]];return <header className="public-header"><div className="site-container site-nav"><Logo/><nav className="nav-links" aria-label="Main navigation">{links.map(([href,label])=><Link key={href} href={href} aria-current={path===href?'page':undefined}>{label}</Link>)}</nav><div className="nav-right"><LanguagePicker/><Link href="/login" className="button dark small nav-member">{tr('Member access','Acceso de miembros','Mitgliederzugang')}<ArrowUpRight/></Link><Sheet><SheetTrigger asChild><button className="mobile-menu-button" aria-label={tr('Open menu','Abrir menú','Menü öffnen')}><Menu/></button></SheetTrigger><SheetContent className="mobile-nav" side="right"><SheetTitle><Logo/></SheetTitle><nav>{links.map(([href,label])=><SheetClose asChild key={href}><Link href={href}>{label}</Link></SheetClose>)}<SheetClose asChild><Link className="button dark" href="/login">{tr('Member access','Acceso de miembros','Mitgliederzugang')}<ArrowRight/></Link></SheetClose></nav></SheetContent></Sheet></div></div></header>}
export function ExploreDock(){const {tr,user,role}=useElevation();const path=usePathname();const items:[string,string,typeof Globe2][]=[['/',tr('Website','Sitio web','Website'),Globe2]];if(user)items.push(['/member',tr('Member area','Miembros','Mitglieder'),BookOpen]);if(role==='admin')items.push(['/admin',tr('Admin studio','Administración','Verwaltung'),LayoutDashboard]);if(!user)items.push(['/login',tr('Sign in','Iniciar sesión','Anmelden'),LayoutDashboard]);return <nav className="explore-dock" aria-label={tr('Explore the platform','Explorar la plataforma','Plattform erkunden')}><span className="dock-label">{tr('EXPLORE','EXPLORAR','ENTDECKEN')}</span>{items.map(([href,title,Icon])=><Link key={href} href={href} className={(href==='/'?!path.startsWith('/member')&&!path.startsWith('/admin'):path.startsWith(href))?'active':''}>{typeof Icon!=='string'&&<Icon/>}{title}</Link>)}</nav>}
export function PublicFooter(){const {tr}=useElevation();return <footer className="footer"><div className="site-container"><div className="footer-main"><div><Logo/><p>{tr('A wide-angle view of the Word of God. Studied with clarity, context, and an open Bible.','Una visión amplia de la Palabra de Dios. Con claridad, contexto y una Biblia abierta.','Ein weiter Blick auf Gottes Wort. Mit Klarheit, Kontext und einer offenen Bibel.')}</p></div><nav className="footer-links"><Link href="/">{tr('Home','Inicio','Startseite')}</Link><Link href="/studies">{tr('The studies','Los estudios','Die Studien')}</Link><Link href="/#about">{tr('Our story','Nuestra historia','Unsere Geschichte')}</Link><Link href="/member">{tr('Member area','Miembros','Mitglieder')}</Link><Link href="/admin">{tr('Admin studio','Administración','Verwaltung')}</Link><Link href="/contact">{tr('Contact','Contacto','Kontakt')}</Link></nav></div><div className="footer-bottom"><span>© 2026 Elevation Bible Study</span><span>{tr('The Thousand-Foot View','La perspectiva desde lo alto','Der Blick aus der Höhe')} · EN / ES / DE</span></div></div></footer>}
export function CourseCover({course,index=0}:{course:Course;index?:number}){const {tr,tx}=useElevation();return <div className={`course-cover ${course.theme}`}><div className="cover-top"><span className="cover-kicker">ELEVATION / {tr('STUDIES','ESTUDIOS','STUDIEN')}</span><span className="cover-number">{String(index+1).padStart(2,'0')}</span></div><div className="cover-shape"/><div className="cover-title">{tx(course.title)}</div><div className="cover-bottom"><small>{course.category==='foundations'?tr('START HERE','EMPIEZA AQUÍ','HIER BEGINNEN'):course.category==='prophecy'?tr('THE FLAGSHIP SERIES','LA SERIE PRINCIPAL','DIE SCHWERPUNKTREIHE'):tr('THE NEW TESTAMENT','EL NUEVO TESTAMENTO','DAS NEUE TESTAMENT')}</small><span className="cover-play">{course.status==='draft'?<Mountain/>:<Play/>}</span></div></div>}
export function CourseCard({course,index=0,member=false}:{course:Course;index?:number;member?:boolean}){const {tr,tx,completed}=useElevation();const count=completed.filter(k=>k.startsWith(course.id+'-')).length;return <Link href={`/member/lesson/${course.id}`} className="course-card"><CourseCover course={course} index={index}/><div className="course-info"><div className="course-meta"><span>{course.count?`${course.count} ${tr('sessions','sesiones','Einheiten')}`:tr('In production','En producción','In Vorbereitung')}</span><span>{course.count?tr('~30 min each','~30 min cada una','je ~30 Min.'):tr('Coming soon','Próximamente','Demnächst')}</span></div><h3>{tx(course.title)}</h3><p>{tx(course.subtitle)}</p>{member&&course.count>0&&<div className="course-progress"><Progress value={Math.min(100,count/course.count*100)} aria-label={tr('Course progress','Progreso del curso','Kursfortschritt')}/><span>{Math.round(count/course.count*100)}%</span></div>}</div></Link>}
export function VideoModal({open,setOpen}:{open:boolean;setOpen:(v:boolean)=>void}){const {tr}=useElevation();return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="video-dialog"><div className="video-dialog-art"><span><Play/></span></div><div className="video-dialog-content"><Eyebrow gold>{tr('A new perspective','Una nueva perspectiva','Eine neue Perspektive')}</Eyebrow><DialogTitle className="mt-4">{tr('The story is coming into focus.','La historia empieza a verse con claridad.','Die Geschichte wird klarer.')}</DialogTitle><DialogDescription>{tr('The introduction film is coming soon. In the meantime, explore the study experience, open a session, and see how your learning journey will unfold.','El video de introducción llegará pronto. Mientras tanto, explora la experiencia de estudio y abre una sesión para conocer tu recorrido.','Der Einführungsfilm kommt bald. Erkunde inzwischen die Studien, öffne eine Einheit und entdecke deinen Lernweg.')}</DialogDescription><Link href="/member/lesson/interpretation" className="button gold" onClick={()=>setOpen(false)}>{tr('Explore the first study','Explorar el primer estudio','Die erste Studie entdecken')}<ArrowRight/></Link></div></DialogContent></Dialog>}
