/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchLessonIdRouteImport } from './routes/watch.$lessonId'
import { Route as SeriesSlugRouteImport } from './routes/series.$slug'
import { Route as AdminSeriesRouteImport } from './routes/admin.series'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminSeriesIdRouteImport } from './routes/admin.series.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchLessonIdRoute = WatchLessonIdRouteImport.update({
  id: '/watch/$lessonId',
  path: '/watch/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSlugRoute = SeriesSlugRouteImport.update({
  id: '/series/$slug',
  path: '/series/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeriesRoute = AdminSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeriesIdRoute = AdminSeriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminSeriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/series': typeof AdminSeriesRouteWithChildren
  '/series/$slug': typeof SeriesSlugRoute
  '/watch/$lessonId': typeof WatchLessonIdRoute
  '/admin/series/$id': typeof AdminSeriesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/series': typeof AdminSeriesRouteWithChildren
  '/series/$slug': typeof SeriesSlugRoute
  '/watch/$lessonId': typeof WatchLessonIdRoute
  '/admin/series/$id': typeof AdminSeriesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/series': typeof AdminSeriesRouteWithChildren
  '/series/$slug': typeof SeriesSlugRoute
  '/watch/$lessonId': typeof WatchLessonIdRoute
  '/admin/series/$id': typeof AdminSeriesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/library'
    | '/login'
    | '/signup'
    | '/admin/members'
    | '/admin/series'
    | '/series/$slug'
    | '/watch/$lessonId'
    | '/admin/series/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/library'
    | '/login'
    | '/signup'
    | '/admin/members'
    | '/admin/series'
    | '/series/$slug'
    | '/watch/$lessonId'
    | '/admin/series/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/library'
    | '/login'
    | '/signup'
    | '/admin/members'
    | '/admin/series'
    | '/series/$slug'
    | '/watch/$lessonId'
    | '/admin/series/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SeriesSlugRoute: typeof SeriesSlugRoute
  WatchLessonIdRoute: typeof WatchLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$lessonId': {
      id: '/watch/$lessonId'
      path: '/watch/$lessonId'
      fullPath: '/watch/$lessonId'
      preLoaderRoute: typeof WatchLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$slug': {
      id: '/series/$slug'
      path: '/series/$slug'
      fullPath: '/series/$slug'
      preLoaderRoute: typeof SeriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/series': {
      id: '/admin/series'
      path: '/series'
      fullPath: '/admin/series'
      preLoaderRoute: typeof AdminSeriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/series/$id': {
      id: '/admin/series/$id'
      path: '/$id'
      fullPath: '/admin/series/$id'
      preLoaderRoute: typeof AdminSeriesIdRouteImport
      parentRoute: typeof AdminSeriesRoute
    }
  }
}

interface AdminSeriesRouteChildren {
  AdminSeriesIdRoute: typeof AdminSeriesIdRoute
}

const AdminSeriesRouteChildren: AdminSeriesRouteChildren = {
  AdminSeriesIdRoute: AdminSeriesIdRoute,
}

const AdminSeriesRouteWithChildren = AdminSeriesRoute._addFileChildren(
  AdminSeriesRouteChildren,
)

interface AdminRouteChildren {
  AdminMembersRoute: typeof AdminMembersRoute
  AdminSeriesRoute: typeof AdminSeriesRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMembersRoute: AdminMembersRoute,
  AdminSeriesRoute: AdminSeriesRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SeriesSlugRoute: SeriesSlugRoute,
  WatchLessonIdRoute: WatchLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
